# Generated by Django 4.0.2 on 2022-09-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image_url',
            field=models.URLField(max_length=300, null=True),
        ),
    ]
